"use server";import {db} from "@/lib/db";import {setSession,clearSession,getSession} from "@/lib/auth";import bcrypt from "bcryptjs";import {redirect} from "next/navigation";import {revalidatePath} from "next/cache";import {slugify} from "@/lib/utils";
async function requireAdmin(){const id=await getSession();if(!id)throw new Error("Unauthorized");const user=await db.user.findUnique({where:{id}});if(!user)throw new Error("Unauthorized")}
export async function login(form:FormData){const email=String(form.get("email")||"").toLowerCase().trim();const password=String(form.get("password")||"");const user=await db.user.findUnique({where:{email}});if(!user||!(await bcrypt.compare(password,user.password)))redirect("/admin/login?error=1");await setSession(user.id);redirect("/admin")}
export async function logout(){await clearSession();redirect("/admin/login")}
const s=(f:FormData,k:string)=>String(f.get(k)||"").trim();const b=(f:FormData,k:string)=>f.get(k)==="on";const array=(v:string)=>JSON.stringify(v.split("\n").map(x=>x.trim()).filter(Boolean));
export async function saveProject(f:FormData){await requireAdmin();const id=s(f,"id");const data={slug:slugify(s(f,"slug")||s(f,"title")),title:s(f,"title"),location:s(f,"location"),category:s(f,"category")||"Residence",status:s(f,"status")||"Ongoing",excerpt:s(f,"excerpt"),description:s(f,"description"),image:s(f,"image"),gallery:array(s(f,"gallery")),amenities:array(s(f,"amenities")),price:s(f,"price")||null,bedrooms:s(f,"bedrooms")||null,size:s(f,"size")||null,published:b(f,"published"),featured:b(f,"featured")};if(!data.title||!data.slug||!data.image)throw new Error("Title, slug and image required");if(id)await db.project.update({where:{id},data});else await db.project.create({data});revalidatePath("/", "layout");redirect("/admin/projects")}
export async function deleteProject(f:FormData){await requireAdmin();await db.project.delete({where:{id:s(f,"id")}});revalidatePath("/","layout");redirect("/admin/projects")}
export async function savePost(f:FormData){await requireAdmin();const id=s(f,"id");const data={slug:slugify(s(f,"slug")||s(f,"title")),title:s(f,"title"),excerpt:s(f,"excerpt"),content:s(f,"content"),cover:s(f,"cover"),category:s(f,"category")||"Insights",published:b(f,"published")};if(!data.title||!data.slug||!data.cover)throw new Error("Title, slug and cover required");if(id)await db.post.update({where:{id},data});else await db.post.create({data});revalidatePath("/","layout");redirect("/admin/posts")}
export async function deletePost(f:FormData){await requireAdmin();await db.post.delete({where:{id:s(f,"id")}});revalidatePath("/","layout");redirect("/admin/posts")}
export async function saveMedia(f:FormData){await requireAdmin();const id=s(f,"id");const data={title:s(f,"title"),category:s(f,"category")||"Architecture",image:s(f,"image"),caption:s(f,"caption")};if(!data.title||!data.image)throw new Error("Title and image required");if(id)await db.media.update({where:{id},data});else await db.media.create({data});revalidatePath("/media");redirect("/admin/media")}
export async function deleteMedia(f:FormData){await requireAdmin();await db.media.delete({where:{id:s(f,"id")}});revalidatePath("/media");redirect("/admin/media")}
export async function markEnquiryRead(f:FormData){await requireAdmin();const status=s(f,"status")||"New";if(!["New","Reviewed","Qualified","Contacted","Closed"].includes(status))throw new Error("Invalid status");await db.enquiry.update({where:{id:s(f,"id")},data:{read:true,status}});revalidatePath("/admin/enquiries");revalidatePath("/admin/leads")}
export async function updateEnquiryStatus(f:FormData){await requireAdmin();const id=s(f,"id");const status=s(f,"status")||"New";if(!["New","Reviewed","Qualified","Contacted","Closed"].includes(status))throw new Error("Invalid status");await db.enquiry.update({where:{id},data:{status,read:status!=="New"||Boolean(f.get("read")==="on")}});revalidatePath("/admin/enquiries");revalidatePath("/admin/leads")}
export async function saveSettings(f:FormData){await requireAdmin();for(const key of ["phone","email","whatsapp","address","heroTitle","heroSubtitle","conciergeKnowledge"]){await db.setting.upsert({where:{key},update:{value:s(f,key).slice(0,12000)},create:{key,value:s(f,key).slice(0,12000)}})}revalidatePath("/","layout");redirect("/admin/settings?saved=1")}
